### ISSUE TITLE
Improve labels on LED columns for bluetooth pairing

### ISSUE THREAD

**Issue by kmcnaught** [microbit-foundation/ml-trainer#520]
At this point:
![screenshot of pairing process](https://github.com/user-attachments/assets/e16a4413-8663-4ee9-a8e9-a7ea1e3846ee)

The labels are e.g. "Number of LEDs lit in column 5 on the micro:bit display"

This leads to a very verbose screen reader announcement "Number of LEDs lit in column 5 on the micro:bit display  spin button  required  editable  selected 4” (NVDA, default settings)

The most important information is which column you are in - can we just flip it to put the salient info up front?

e.g.  "Column 5 - number of LEDs lit on the micro:bit display"

**Comment by lattaai12** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the FormattedMessage in the PatternColumnInput component to put the column number first in the label, improving screen reader accessibility. The new label format is 'Column {colNum} - number of LEDs lit on the micro:bit display'.

You can review changes in this commit: https://github.com/lattaai12/microbit-foundation-ml-trainer-520/commit/0094b6a0714204d229fd6ffa154d6aad947fecbe.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
